defaults:
  - channel: kafka
  - db: rethinkdb

host: 0.0.0.0
port: 8000
root_path: /api
log_requests: false
cors: false

quota_anonymous: 1_000_000

challenge_difficulty: 1_000_000
challenge_expiration_seconds: 3600

job_expiration_days: 60

page_size_molecular_property_prediction: 100
page_size_atom_property_prediction: 10
page_size_derivative_property_prediction: 10
media_root: /data

mock_infra: false

output_formats:
  - sdf
  - csv
