defaults:
  - channel: kafka
  - db: rethinkdb

host: 0.0.0.0
port: 8000
root_path: /api
log_requests: false
cors: false

quota_mols_per_day_anonymous: 100_000
quota_active_jobs_anonymous: 5

challenge_difficulty: 1_000_000
challenge_expiration_seconds: 3600

# The maximum number of molecules per job is restricted by two factors:
# 1) The variable max_num_molecules_per_job below, and
# 2) The module-specific limit, which is defined by the number of molecules it can process in
#    the time given by max_job_duration_minutes below.
# The actual limit is the minimum of these two values.
max_num_molecules_per_job: 10_000
max_job_duration_minutes: 360

# Jobs are sent in checkpoints to avoid recomputing full jobs if a failure occurs. The checkpoint
# size determines the amount of computation time we are losing (at worst), since the checkpoint has
# to be recomputed.
max_checkpoint_duration_minutes: 15

job_expiration_days: 60

page_size_molecular_property_prediction: 100
page_size_atom_property_prediction: 10
page_size_derivative_property_prediction: 10
media_root: /data

mock_infra: false

output_formats:
  - sdf
  - csv
